// Copyright 2026 Timothé Lapetite and contributors
// Released under the MIT license https://opensource.org/license/MIT/

// Asset Staging - Picks assets from collections and assigns them to points.
// Handles weighted distribution, fitting/scaling, material picking, and socket extraction.

#include "Elements/PCGExAssetStaging.h"

#include "PCGParamData.h"
#include "Core/PCGExAssetCollection.h"
#include "Collections/PCGExMeshCollection.h"
#include "Containers/PCGExScopedContainers.h"
#include "Data/PCGExData.h"
#include "Data/PCGExPointIO.h"
#include "Helpers/PCGExAssetLoader.h"
#include "Helpers/PCGExCollectionsHelpers.h"
#include "Helpers/PCGExRandomHelpers.h"
#include "Helpers/PCGExSocketHelpers.h"


#define LOCTEXT_NAMESPACE "PCGExAssetStagingElement"
#define PCGEX_NAMESPACE AssetStaging

#pragma region UPCGExAssetStagingSettings

#if WITH_EDITOR
void UPCGExAssetStagingSettings::PostEditChangeProperty(struct FPropertyChangedEvent& PropertyChangedEvent)
{
	EntryTypeFilter.PostEditChangeProperty(PropertyChangedEvent);
	Super::PostEditChangeProperty(PropertyChangedEvent);
}
#endif

PCGExData::EIOInit UPCGExAssetStagingSettings::GetMainDataInitializationPolicy() const
{
	// Forward is more efficient but we need Duplicate when pruning since we'll remove points
	if (StealData == EPCGExOptionState::Enabled && !bPruneEmptyPoints) { return PCGExData::EIOInit::Forward; }
	return PCGExData::EIOInit::Duplicate;
}

PCGEX_INITIALIZE_ELEMENT(AssetStaging)
PCGEX_ELEMENT_BATCH_POINT_IMPL(AssetStaging)

TArray<FPCGPinProperties> UPCGExAssetStagingSettings::InputPinProperties() const
{
	TArray<FPCGPinProperties> PinProperties = Super::InputPinProperties();

	if (CollectionSource == EPCGExCollectionSource::AttributeSet)
	{
		PCGEX_PIN_PARAM(PCGExCollections::Labels::SourceAssetCollection, "Attribute set to be used as collection.", Required)
	}

	return PinProperties;
}

TArray<FPCGPinProperties> UPCGExAssetStagingSettings::OutputPinProperties() const
{
	TArray<FPCGPinProperties> PinProperties = Super::OutputPinProperties();
	if (OutputMode == EPCGExStagingOutputMode::CollectionMap)
	{
		PCGEX_PIN_PARAM(PCGExCollections::Labels::OutputCollectionMapLabel, "Collection map generated by a staging node.", Normal)
	}

	if (bDoOutputSockets)
	{
		PCGEX_PIN_POINTS(PCGExStaging::Labels::OutputSocketLabel, "Socket points.", Normal)
	}
	return PinProperties;
}

#pragma endregion

#pragma region FPCGExAssetStagingElement

bool FPCGExAssetStagingElement::Boot(FPCGExContext* InContext) const
{
	if (!FPCGExPointsProcessorElement::Boot(InContext)) { return false; }

	PCGEX_CONTEXT_AND_SETTINGS(AssetStaging)

	if (Settings->bOutputMaterialPicks)
	{
		PCGEX_VALIDATE_NAME(Settings->MaterialAttributePrefix)
		Context->bPickMaterials = true;
	}

	if (Settings->bWriteEntryType)
	{
		PCGEX_VALIDATE_NAME(Settings->EntryTypeAttributeName)
	}

	if (Settings->CollectionSource == EPCGExCollectionSource::Asset)
	{
		PCGExHelpers::LoadBlocking_AnyThreadTpl(Settings->AssetCollection, Context);
		Context->MainCollection = Settings->AssetCollection.Get();
		if (!Context->MainCollection)
		{
			PCGE_LOG(Error, GraphAndLog, FTEXT("Missing asset collection."));
			return false;
		}

		Context->MainCollection->EDITOR_RegisterTrackingKeys(Context);
	}
	else if (Settings->CollectionSource == EPCGExCollectionSource::AttributeSet)
	{
		// CollectionMap can't work with attribute sets because the collection is built at runtime
		// and doesn't have stable asset references to pack
		if (Settings->OutputMode == EPCGExStagingOutputMode::CollectionMap)
		{
			PCGE_LOG(Error, GraphAndLog, FTEXT("Collection Map output is not supported with collections built from attribute sets."));
			return false;
		}

		Context->MainCollection = Settings->AttributeSetDetails.TryBuildCollection(Context, PCGExCollections::Labels::SourceAssetCollection, false);
		if (!Context->MainCollection)
		{
			PCGE_LOG(Error, GraphAndLog, FTEXT("Failed to build collection from attribute set."));
			return false;
		}
	}
	else if (Settings->CollectionSource == EPCGExCollectionSource::Attribute)
	{
		// Per-point mode: defer loading to AdvanceWork since each point may reference a different collection
		PCGEX_VALIDATE_NAME_CONSUMABLE(Settings->CollectionPathAttributeName)

		TArray<FName> Names = {Settings->CollectionPathAttributeName};
		Context->CollectionsLoader = MakeShared<PCGEx::TAssetLoader<UPCGExAssetCollection>>(Context, Context->MainPoints.ToSharedRef(), Names);
	}

	if (Context->bPickMaterials && !Context->MainCollection->IsType(PCGExAssetCollection::TypeIds::Mesh))
	{
		Context->bPickMaterials = false;
		PCGE_LOG(Warning, GraphAndLog, FTEXT("Pick Material is enabled, but the selected collection doesn't support material picking."));
	}

	PCGEX_VALIDATE_NAME(Settings->AssetPathAttributeName)

	if (Settings->WeightToAttribute == EPCGExWeightOutputMode::Raw || Settings->WeightToAttribute == EPCGExWeightOutputMode::Normalized)
	{
		PCGEX_VALIDATE_NAME_CONSUMABLE(Settings->WeightAttributeName)
	}

	if (Settings->OutputMode == EPCGExStagingOutputMode::CollectionMap)
	{
		Context->CollectionPickDatasetPacker = MakeShared<PCGExCollections::FPickPacker>(Context);
	}

	if (Settings->bDoOutputSockets)
	{
		PCGEX_FWD(OutputSocketDetails)
		if (!Context->OutputSocketDetails.Init(Context)) { return false; }

		Context->SocketsCollection = MakeShared<PCGExData::FPointIOCollection>(Context);
		Context->SocketsCollection->OutputPin = PCGExStaging::Labels::OutputSocketLabel;
	}

	return true;
}

#if WITH_EDITOR
FString UPCGExAssetStagingSettings::GetDisplayName() const
{
	FString DisplayName = TEXT("???");
	switch (CollectionSource)
	{
	case EPCGExCollectionSource::Asset:
		if (!AssetCollection.IsNull()) { DisplayName = AssetCollection.GetAssetName(); }
		break;
	case EPCGExCollectionSource::AttributeSet:
		DisplayName = TEXT("Set");
		break;
	case EPCGExCollectionSource::Attribute:
		DisplayName = CollectionPathAttributeName.ToString();
		break;
	}

	return TEXT("Staging [ ") + DisplayName + TEXT(" ]");
}
#endif

#pragma endregion

#pragma region FPCGExAssetStagingContext

void FPCGExAssetStagingContext::RegisterAssetDependencies()
{
	FPCGExPointsProcessorContext::RegisterAssetDependencies();

	PCGEX_SETTINGS_LOCAL(AssetStaging)

	// For AttributeSet mode, we built the collection in Boot but assets aren't loaded yet.
	// Register them so PCG's dependency system will preload before we process.
	if (Settings->CollectionSource == EPCGExCollectionSource::AttributeSet)
	{
		MainCollection->GetAssetPaths(GetRequiredAssets(), PCGExAssetCollection::ELoadingFlags::Recursive);
	}
}

#pragma endregion

#pragma region FPCGExAssetStagingElement (continued)

void FPCGExAssetStagingElement::PostLoadAssetsDependencies(FPCGExContext* InContext) const
{
	FPCGExPointsProcessorElement::PostLoadAssetsDependencies(InContext);

	PCGEX_CONTEXT_AND_SETTINGS(AssetStaging)

	if (Settings->CollectionSource == EPCGExCollectionSource::AttributeSet)
	{
		// Now that PCG has loaded the assets, rebuild staging data (bounds, paths, etc.)
		Context->MainCollection->RebuildStagingData(true);
	}
}

bool FPCGExAssetStagingElement::PostBoot(FPCGExContext* InContext) const
{
	PCGEX_CONTEXT_AND_SETTINGS(AssetStaging)

	// Skip validation for Attribute mode - collections load per-point in AdvanceWork
	if (Settings->CollectionSource != EPCGExCollectionSource::Attribute)
	{
		check(Context->MainCollection)
		if (Context->MainCollection->LoadCache()->IsEmpty())
		{
			if (!Settings->bQuietEmptyCollectionError)
			{
				PCGE_LOG_C(Error, GraphAndLog, Context, FTEXT("Selected asset collection is empty."));
			}

			return false;
		}
	}

	return FPCGExPointsProcessorElement::PostBoot(InContext);
}

bool FPCGExAssetStagingElement::AdvanceWork(FPCGExContext* InContext, const UPCGExSettings* InSettings) const
{
	TRACE_CPUPROFILER_EVENT_SCOPE(FPCGExAssetStagingElement::Execute);

	PCGEX_CONTEXT_AND_SETTINGS(AssetStaging)
	PCGEX_EXECUTION_CHECK

	PCGEX_ON_INITIAL_EXECUTION
	{
		if (Context->CollectionsLoader)
		{
			Context->SetState(PCGExCommon::States::State_WaitingOnAsyncWork);

			if (!Context->CollectionsLoader->Start(Context->GetTaskManager()))
			{
				return Context->CancelExecution(TEXT("Failed to find any collections to load."));
			}
		}
		else
		{
			if (!Context->StartBatchProcessingPoints(
				[&](const TSharedPtr<PCGExData::FPointIO>& Entry) { return true; },
				[&](const TSharedPtr<PCGExPointsMT::IBatch>& NewBatch)
				{
					NewBatch->bRequiresWriteStep = Settings->bPruneEmptyPoints;
				}))
			{
				return Context->CancelExecution(TEXT("Could not find any points to process."));
			}
		}
	}

	PCGEX_ON_ASYNC_STATE_READY(PCGExCommon::States::State_WaitingOnAsyncWork)
	{
		if (Context->CollectionsLoader && Context->CollectionsLoader->IsEmpty())
		{
			return Context->CancelExecution(TEXT("Failed to load any collection from points."));
		}

		for (const TPair<PCGExValueHash, TObjectPtr<UPCGExAssetCollection>>& Pair : Context->CollectionsLoader->AssetsMap)
		{
			Pair.Value->LoadCache();
		}

		if (!Context->StartBatchProcessingPoints(
			[&](const TSharedPtr<PCGExData::FPointIO>& Entry) { return true; },
			[&](const TSharedPtr<PCGExPointsMT::IBatch>& NewBatch)
			{
				NewBatch->bSkipCompletion = true;
			}))
		{
			return Context->CancelExecution(TEXT("Could not find any points to process."));
		}
	}

	PCGEX_POINTS_BATCH_PROCESSING(PCGExCommon::States::State_Done)

	Context->MainPoints->StageOutputs();

	if (Settings->OutputMode == EPCGExStagingOutputMode::CollectionMap)
	{
		UPCGParamData* OutputSet = Context->ManagedObjects->New<UPCGParamData>();
		Context->CollectionPickDatasetPacker->PackToDataset(OutputSet);

		FPCGTaggedData& OutData = Context->OutputData.TaggedData.Emplace_GetRef();
		OutData.Pin = PCGExCollections::Labels::OutputCollectionMapLabel;
		OutData.Data = OutputSet;
	}

	if (Context->SocketsCollection) { Context->SocketsCollection->StageOutputs(); }

	return Context->TryComplete();
}

#pragma endregion

#pragma region PCGExAssetStaging::FProcessor

namespace PCGExAssetStaging
{
	bool FProcessor::Process(const TSharedPtr<PCGExMT::FTaskManager>& InTaskManager)
	{
		TRACE_CPUPROFILER_EVENT_SCOPE(PCGExAssetStaging::Process);

		PointDataFacade->bSupportsScopedGet = Context->bScopedAttributeGet;

		if (!IProcessor::Process(InTaskManager)) { return false; }

		PCGEX_INIT_IO(PointDataFacade->Source, Settings->GetMainDataInitializationPolicy())

		NumPoints = PointDataFacade->GetNum();

		if (Context->bPickMaterials)
		{
			CachedPicks.Init(nullptr, NumPoints);
			MaterialPick.Init(-1, NumPoints);
		}

		FittingHandler.ScaleToFit = Settings->ScaleToFit;
		FittingHandler.Justification = Settings->Justification;

		if (!FittingHandler.Init(ExecutionContext, PointDataFacade)) { return false; }

		Variations = Settings->Variations;
		Variations.Init(Settings->Seed);

		Source = MakeShared<PCGExCollections::FCollectionSource>(PointDataFacade);
		Source->DistributionSettings = Settings->DistributionSettings;
		Source->EntryDistributionSettings = Settings->EntryDistributionSettings;

		if (Settings->CollectionSource == EPCGExCollectionSource::Attribute)
		{
			if (!Source->Init(Context->CollectionsLoader->AssetsMap, Context->CollectionsLoader->GetKeys(PointDataFacade->Source->IOIndex)))
			{
				return false;
			}
		}
		else
		{
			if (!Source->Init(Context->MainCollection)) { return false; }
		}

		if (Settings->bDoOutputSockets) { SocketHelper = MakeShared<PCGExCollections::FSocketHelper>(&Context->OutputSocketDetails, NumPoints); }

		bOutputWeight = Settings->WeightToAttribute != EPCGExWeightOutputMode::NoOutput;
		bNormalizedWeight = Settings->WeightToAttribute != EPCGExWeightOutputMode::Raw;
		bOneMinusWeight = Settings->WeightToAttribute == EPCGExWeightOutputMode::NormalizedInverted || Settings->WeightToAttribute == EPCGExWeightOutputMode::NormalizedInvertedToDensity;

		if (Settings->WeightToAttribute == EPCGExWeightOutputMode::Raw)
		{
			WeightWriter = PointDataFacade->GetWritable<int32>(Settings->WeightAttributeName, PCGExData::EBufferInit::New);
		}
		else if (Settings->WeightToAttribute == EPCGExWeightOutputMode::Normalized)
		{
			NormalizedWeightWriter = PointDataFacade->GetWritable<double>(Settings->WeightAttributeName, PCGExData::EBufferInit::New);
		}

		if (Settings->bWriteEntryType)
		{
			EntryTypeWriter = PointDataFacade->GetWritable<FName>(Settings->EntryTypeAttributeName, NAME_None, true, PCGExData::EBufferInit::Inherit);
		}

		if (Settings->bWriteTranslation)
		{
			TranslationWriter = PointDataFacade->GetWritable<FVector>(Settings->TranslationAttributeName, FVector::ZeroVector, true, PCGExData::EBufferInit::Inherit);
		}

		// bInherit: if the attribute already exists, preserve values for invalid points instead of clearing them
		if (Settings->OutputMode == EPCGExStagingOutputMode::Attributes)
		{
			bInherit = PointDataFacade->GetIn()->Metadata->HasAttribute(Settings->AssetPathAttributeName);
			PathWriter = PointDataFacade->GetWritable<FSoftObjectPath>(Settings->AssetPathAttributeName, bInherit ? PCGExData::EBufferInit::Inherit : PCGExData::EBufferInit::New);
		}
		else
		{
			bInherit = PointDataFacade->GetIn()->Metadata->HasAttribute(PCGExCollections::Labels::Tag_EntryIdx);
			HashWriter = PointDataFacade->GetWritable<int64>(PCGExCollections::Labels::Tag_EntryIdx, bInherit ? PCGExData::EBufferInit::Inherit : PCGExData::EBufferInit::New);
		}

		EPCGPointNativeProperties AllocateFor = EPCGPointNativeProperties::None;

		AllocateFor |= EPCGPointNativeProperties::BoundsMin;
		AllocateFor |= EPCGPointNativeProperties::BoundsMax;
		AllocateFor |= EPCGPointNativeProperties::Transform;
		if (bOutputWeight && !WeightWriter && !NormalizedWeightWriter)
		{
			// No explicit weight attribute - fall back to writing weight into Density
			bUsesDensity = true;
			AllocateFor |= EPCGPointNativeProperties::Density;
		}

		PointDataFacade->GetOut()->AllocateProperties(AllocateFor);

		if (Settings->bPruneEmptyPoints) { Mask.Init(1, PointDataFacade->GetNum()); }

		StartParallelLoopForPoints();

		return true;
	}

	void FProcessor::PrepareLoopScopesForPoints(const TArray<PCGExMT::FScope>& Loops)
	{
		// Thread-safe per-scope max tracking for material slot indices
		HighestSlotIndex = MakeShared<PCGExMT::TScopedNumericValue<int8>>(Loops, -1);
	}

	void FProcessor::ProcessPoints(const PCGExMT::FScope& Scope)
	{
		TRACE_CPUPROFILER_EVENT_SCOPE(PCGEx::AssetStaging::ProcessPoints);

		PointDataFacade->Fetch(Scope);
		FilterScope(Scope);

		UPCGBasePointData* OutPointData = PointDataFacade->GetOut();

		const TPCGValueRange<FTransform> OutTransforms = OutPointData->GetTransformValueRange(false);
		const TPCGValueRange<FVector> OutBoundsMin = OutPointData->GetBoundsMinValueRange(false);
		const TPCGValueRange<FVector> OutBoundsMax = OutPointData->GetBoundsMaxValueRange(false);
		const TConstPCGValueRange<int32> Seeds = OutPointData->GetConstSeedValueRange();
		const TPCGValueRange<float> Densities = bUsesDensity ? OutPointData->GetDensityValueRange(false) : TPCGValueRange<float>();

		int32 LocalNumInvalid = 0;

		// Handles points that fail distribution or filtering.
		// When bInherit is true, we preserve existing attribute values (from previous staging pass).
		// Otherwise we either mark for pruning or write sentinel values.
		auto InvalidPoint = [&](const int32 Index)
		{
			if (bInherit) { return; } // Keep existing values from upstream staging

			if (Settings->bPruneEmptyPoints)
			{
				Mask[Index] = 0;
				LocalNumInvalid++;
				return;
			}

			// Write sentinel values so downstream nodes can detect unstaged points
			if (PathWriter) { PathWriter->SetValue(Index, FSoftObjectPath{}); }
			else { HashWriter->SetValue(Index, -1); }

			if (bOutputWeight)
			{
				if (WeightWriter) { WeightWriter->SetValue(Index, -1); }
				else if (NormalizedWeightWriter) { NormalizedWeightWriter->SetValue(Index, -1); }
			}

			if (Context->bPickMaterials) { MaterialPick[Index] = -1; }
		};

		const UPCGComponent* Component = Context->GetComponent();
		int32 LocalHighestSlotIndex = 0;
		FRandomStream RandomSource;

		const bool bFilterEntryType = Settings->bDoFilterEntryType;
		const FPCGExStagedTypeFilterDetails& EntryTypeFilter = Settings->EntryTypeFilter;

		PCGEX_SCOPE_LOOP(Index)
		{
			PCGExCollections::FDistributionHelper* Helper = nullptr;
			PCGExCollections::FMicroDistributionHelper* MicroHelper = nullptr;

			if (!PointFilterCache[Index] || !Source->TryGetHelpers(Index, Helper, MicroHelper))
			{
				InvalidPoint(Index);
				continue;
			}

			const int32 Seed = PCGExRandomHelpers::GetSeed(Seeds[Index], Helper->Details.SeedComponents, Helper->Details.LocalSeed, Settings, Component);

			FPCGExEntryAccessResult Result = Helper->GetEntry(Index, Seed);

			if (!Result.IsValid()
				|| !Result.Entry->Staging.Bounds.IsValid
				|| (bFilterEntryType && !EntryTypeFilter.Matches(Result.Host->GetTypeId())))
			{
				InvalidPoint(Index);
				continue;
			}

			const FPCGExAssetCollectionEntry* Entry = Result.Entry;
			const UPCGExAssetCollection* EntryHost = Result.Host;

			FTransform& OutTransform = OutTransforms[Index];
			FVector OutTranslation = FVector::ZeroVector;
			FBox OutBounds = Entry->Staging.Bounds;
			int16 SecondaryIndex = -1; // Material variant index within the entry

			const FPCGExAssetStagingData& Staging = Entry->Staging;
			const FPCGExFittingVariations& EntryVariations = Entry->GetVariations(EntryHost);

			// MicroCache holds per-entry sub-distribution data (e.g., material variants for meshes).
			// SecondaryIndex selects which variant to use for this point.
			if (const PCGExAssetCollection::FMicroCache* MicroCache = Entry->MicroCache.Get();
				MicroHelper && MicroCache && MicroCache->GetTypeId() == PCGExAssetCollection::TypeIds::Mesh)
			{
				const PCGExMeshCollection::FMicroCache* EntryMicroCache = static_cast<const PCGExMeshCollection::FMicroCache*>(MicroCache);
				SecondaryIndex = MicroHelper->GetPick(EntryMicroCache, Index, Seed);

				if (Context->bPickMaterials)
				{
					MaterialPick[Index] = SecondaryIndex;
					CachedPicks[Index] = Entry;
					// Track highest slot index seen so we know how many material attributes to create
					LocalHighestSlotIndex = FMath::Max(LocalHighestSlotIndex, EntryMicroCache->GetHighestIndex());
				}
			}
			else if (Context->bPickMaterials)
			{
				MaterialPick[Index] = -1;
			}

			if (bOutputWeight)
			{
				double Weight = bNormalizedWeight ? static_cast<double>(Entry->Weight) / static_cast<double>(Context->MainCollection->LoadCache()->WeightSum) : Entry->Weight;
				if (bOneMinusWeight) { Weight = 1 - Weight; }
				if (WeightWriter) { WeightWriter->SetValue(Index, Weight); }
				if (NormalizedWeightWriter) { NormalizedWeightWriter->SetValue(Index, Weight); }
				else { Densities[Index] = Weight; }
			}

			if (PathWriter) { PathWriter->SetValue(Index, Staging.Path); }
			else { HashWriter->SetValue(Index, Context->CollectionPickDatasetPacker->GetPickIdx(EntryHost, Staging.InternalIndex, SecondaryIndex)); }

			RandomSource.Initialize(PCGExRandomHelpers::GetSeed(Seed, Variations.Seed));

			// "Before" variations modify asset bounds before fitting, affecting scale-to-fit calculation.
			// "After" variations apply to the final transform without changing bounds.
			if (Variations.bEnabledBefore)
			{
				FTransform LocalXForm = FTransform::Identity;
				Variations.Apply(RandomSource, LocalXForm, EntryVariations, EPCGExVariationMode::Before);
				FittingHandler.ComputeLocalTransform(Index, LocalXForm, OutTransform, OutBounds, OutTranslation);
			}
			else
			{
				FittingHandler.ComputeTransform(Index, OutTransform, OutBounds, OutTranslation);
			}

			if (TranslationWriter) { TranslationWriter->SetValue(Index, OutTranslation); }

			OutBoundsMin[Index] = OutBounds.Min;
			OutBoundsMax[Index] = OutBounds.Max;

			if (Variations.bEnabledAfter)
			{
				Variations.Apply(RandomSource, OutTransform, EntryVariations, EPCGExVariationMode::After);
			}

			if (SocketHelper)
			{
				uint64 EntryHash = PCGEx::H64(EntryHost->GetUniqueID(), Staging.InternalIndex);
				SocketHelper->Add(Index, EntryHash, Entry);
			}

			if (EntryTypeWriter)
			{
				EntryTypeWriter->SetValue(Index, Result.Host->GetTypeId());
			}
		}

		// Merge per-scope max into shared tracker (thread-safe)
		HighestSlotIndex->Set(Scope, FMath::Max(LocalHighestSlotIndex, HighestSlotIndex->Get(Scope)));
		FPlatformAtomics::InterlockedAdd(&NumInvalid, LocalNumInvalid);
	}

	void FProcessor::OnPointsProcessingComplete()
	{
		if (SocketHelper) { SocketHelper->Compile(TaskManager, PointDataFacade, Context->SocketsCollection); }

		if (Context->bPickMaterials)
		{
			// Create one attribute per material slot used across all picked entries.
			// HighestSlotIndex was tracked during ProcessPoints to know how many we need.
			int8 WriterCount = HighestSlotIndex->Max() + 1;
			if (Settings->MaxMaterialPicks > 0) { WriterCount = Settings->MaxMaterialPicks; }

			if (WriterCount > 0)
			{
				MaterialWriters.Init(nullptr, WriterCount);

				for (int i = 0; i < WriterCount; i++)
				{
					const FName AttributeName = FName(FString::Printf(TEXT("%s_%d"), *Settings->MaterialAttributePrefix.ToString(), i));
					MaterialWriters[i] = PointDataFacade->GetWritable<FSoftObjectPath>(AttributeName, FSoftObjectPath(), true, PCGExData::EBufferInit::New);
				}

				// Second parallel pass to write material picks (separate from main loop for buffer allocation)
				StartParallelLoopForRange(NumPoints);
				return;
			}

			PCGE_LOG_C(Warning, GraphAndLog, Context, FTEXT("No material were picked -- no attribute will be written."));
		}

		OnRangeProcessingComplete();
	}

	// Writes material override paths to per-slot attributes based on the picks made in ProcessPoints
	void FProcessor::ProcessRange(const PCGExMT::FScope& Scope)
	{
		PCGEX_SCOPE_LOOP(Index)
		{
			const int32 Pick = MaterialPick[Index];

			if (Pick == -1 || (Settings->bPruneEmptyPoints && !Mask[Index])) { continue; }

			const FPCGExMeshCollectionEntry* Entry = static_cast<const FPCGExMeshCollectionEntry*>(CachedPicks[Index]);
			if (Entry->MaterialVariants == EPCGExMaterialVariantsMode::None) { continue; }

			// Single mode: one material slot override
			if (Entry->MaterialVariants == EPCGExMaterialVariantsMode::Single)
			{
				if (!MaterialWriters.IsValidIndex(Entry->SlotIndex)) { continue; }
				MaterialWriters[Entry->SlotIndex]->SetValue(Index, Entry->MaterialOverrideVariants[Pick].Material.ToSoftObjectPath());
			}
			// Multi mode: multiple material slot overrides per variant
			else if (Entry->MaterialVariants == EPCGExMaterialVariantsMode::Multi)
			{
				const FPCGExMaterialOverrideCollection& MEntry = Entry->MaterialOverrideVariantsList[Pick];

				for (int i = 0; i < MEntry.Overrides.Num(); i++)
				{
					const FPCGExMaterialOverrideEntry& SlotEntry = MEntry.Overrides[i];

					const int32 SlotIndex = SlotEntry.SlotIndex == -1 ? 0 : SlotEntry.SlotIndex;
					if (!MaterialWriters.IsValidIndex(SlotIndex)) { continue; }
					MaterialWriters[SlotIndex]->SetValue(Index, SlotEntry.Material.ToSoftObjectPath());
				}
			}
		}
	}

	void FProcessor::OnRangeProcessingComplete()
	{
		PointDataFacade->WriteBuffers(
			TaskManager,
			[PCGEX_ASYNC_THIS_CAPTURE]()
			{
				PCGEX_ASYNC_THIS
				This->Write();
			});
	}

	void FProcessor::Write()
	{
		if (Settings->bPruneEmptyPoints)
		{
			// Release Source before Gather since Gather will invalidate indices it references
			Source.Reset();
			(void)PointDataFacade->Source->Gather(Mask);
		}
	}
}

#pragma endregion

#undef LOCTEXT_NAMESPACE
#undef PCGEX_NAMESPACE
